#' Colocalization analysis
#'
#' This function performs colocalization analysis on 2 channels of the user's choosing.
#' Relies on data generated by micimportR.
#' @keywords microscopR
#' @export
#' @examples
#' colocalizeR()

ColocalizeR <- function(imglist, chan1 = 1, fluor1 = "GFP", chan2 = 2, fluor2 = "mCherry", threshold = 0.05, norm = FALSE) {
  #Dependencies
  library(foreach)
  library(doMC)
  library(rJava)
  library(EBImage)
  library(RBioFormats)
  #set up parallel processing
  registerDoMC(detectCores())
  #extract lists from imglist
  images_list <- imglist$images_list
  imgmeta <- imglist$imgmeta
  folder_name <- imglist$folder_name
  # #define variables from function arguments
  # chan1 <- chan1
  # fluor1 <- fluor1
  # chan2 <- chan2
  # fluor2 <- fluor2

  output_df <- foreach (i = seq_along(images_list), .combine = rbind) %dopar% {
    #take image name from supplied metadata
    img_name <- imgmeta[[i]]
    #Read number of frames before continuing, move to next file if <2
    if (numberOfFrames(images_list[[i]]) >= 2) {
      chan1_dt_16bit <- data.table(getFrame(images_list[[i]], chan1))
      chan2_dt_16bit <- data.table(getFrame(images_list[[i]], chan2))
    } else {
      return("Only images with 2 channels or more can be analysed")
    }
    #Start pdf, plots will go in here
    pdf(paste(folder_name, "_", i, "_", img_name, ".pdf", sep = ""), paper = "a4")

    #Plot histograms to show distributions of intensities
    #Data frames cannot be plotted as histograms, hence as.matrix
    hist(as.matrix(chan1_dt_16bit), main = "Pre-normalization", xlab = paste(fluor1, "intensity"))
    hist(as.matrix(chan2_dt_16bit), main = "Pre-normalization", xlab = paste(fluor2, "intensity"))

    #Scatter plot of un-normalized data
    #Scatter plot takes numeric vectors as input, this line also converts the data frames
    smoothScatter(as.vector(as.matrix(chan1_dt_16bit)), as.vector(as.matrix(chan2_dt_16bit)), main = "Pre-normalization", xlab = fluor1, ylab = fluor2)

    #Convert data frames to vectors for further processing
    chan1_vect <- as.vector(as.matrix(chan1_dt_16bit))
    chan2_vect <- as.vector(as.matrix(chan2_dt_16bit))

    #Exclude pixels that are < 20% of max in both channels
    chan1_vect[chan1_vect < (threshold * max(chan1_vect)) & chan2_vect < (threshold * max(chan2_vect))] <- NA

    #Plot new histograms
    hist(chan1_vect, main = "Filter < 20%", xlab = paste(fluor1, "intensity"))
    hist(chan2_vect, main = "Filter < 20%", xlab = paste(fluor2, "intensity"))

    #Normalize channels based on mean fluorescent intensity
    if (norm == TRUE) {
      chan1_relative <- chan1_vect / mean(chan1_vect, na.rm = TRUE)
      chan2_relative <- chan2_vect / mean(chan2_vect, na.rm = TRUE)
    } else {
      chan1_relative <- chan1_vect
      chan2_relative <- chan2_vect
    }

    #Plot histograms, scatter plot, regression line (-1 to force line through origin)

    hist(chan1_relative, main = "Normalized", xlab = paste(1, "intensity"))
    hist(chan2_relative, main = "Normalized", xlab = paste(2, "intensity"))
    smoothScatter(chan1_relative, chan2_relative, main = "Pre-Y axis transformation", xlab = fluor1, ylab = fluor2)
    abline(lm(chan2_relative ~ chan1_relative - 1), col = "red")

    #Calculate how Y-axis (mch_trans) needs to be transformed to reach X=Y
    regression_norm <- lm(chan2_relative ~ chan1_relative - 1)
    chan2_trans <- chan2_relative * (1 / regression_norm$coefficients[1])

    #Place both vectors in data frame, plot new scatter plot
    scatter_dt <- data.table(chan1_relative, chan2_trans)
    smoothScatter(scatter_dt, xlim = c(0, max(scatter_dt$chan1_relative, na.rm = TRUE)), ylim = c(0, max(scatter_dt$chan2_trans, na.rm = TRUE)), main = "Final", xlab = fluor1, ylab = fluor2)
    abline(lm(chan2_trans ~ chan1_relative - 1, data = scatter_dt), col = "red")

    #Calculate fineal linear regression
    final_model <- lm(chan2_trans ~ chan1_relative - 1, data = scatter_dt)
    dev.off()
    #Create .txt file to output regression results
    sink(file = paste(folder_name, "_", i, "_", img_name, ".txt", sep = ""), type = "output")
    print(summary(final_model))
    sink()
    #Print to console to keep track of progress
    #print(i)
    img_ident <- paste(folder_name, "_", img_name, sep = "")
    data.frame("img" = img_ident, "Rsquared"=summary(final_model)$adj.r.squared)
  }

  return(output_df)
}
